### ISSUE TITLE
execSync incompatible with installed nodejs

### ISSUE THREAD

**Issue by heresandyboy** [jbavari/cordova-deploy#3]
Hi, I am really excited to try this out on my Windows 7 Dev machine, I have created and populated a hockey.json file in the root of the project. When executing "cordova-deploy --build --android --hockey" I am getting the following error, any help would be appreciated. I have yet to try on the Mac, I'll do that tomorrow.

execSync incompatible with installed nodejs

My Nodejs version is  v0.10.31

Console Output:

> cordova-deploy --build --android --hockey
> [Error: %1 is not a valid Win32 application.
> C:\Users\%USER%\AppData\Roaming\npm\node_modules\cordova-deploy\node_modules\execSync\win32\v0.10\shell.
> node]
> 
> C:\Users\%USER%\AppData\Roaming\npm\node_modules\cordova-deploy\node_modules\execSync\index.js:24
>       throw new Error('execSync incompatible with installed nodejs');
>             ^
> Error: execSync incompatible with installed nodejs
>     at Object.<anonymous> (C:\Users\%USER%\AppData\Roaming\npm\node_modules\cordova-deploy\node_modules\
> execSync\index.js:24:13)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (C:\Users\%USER%\AppData\Roaming\npm\node_modules\cordova-deploy\lib\builder.j
> s:1:78)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)

**Comment by jbavari** [comment]
I'll be addressing this in [this issue](https://github.com/jbavari/cordova-deploy/issues/6)
