### ISSUE TITLE
Replace execSync with shelljs

### ISSUE THREAD

**Issue by jbavari** [jbavari/cordova-deploy#6]
Shelljs is known to be better cross platform with Windows / Mac, so use that instead.

**Comment by sagrawal31** [comment]
On running command:

``` shell
cordova-deploy --build --ios --hockey
```

I'm getting the following error in Mac:

``` javascript
module.js:327
    throw err;
    ^

Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova-deploy/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by sagrawal31** [comment]
Using forked https://github.com/bamlab/cordova-deploy worked for me
